[package]
name = "vizz"
version = "0.1.0"
edition = "2021"

[dependencies]
vizz-backend = { path="../vizz-backend/" }
vizz-types = { path="../vizz-types/" }

[dev-dependencies]
wgpu = "24.0"
pollster = "0.4"
env_logger = "0.11"
bytemuck = "1.21"
